services:
  urlshortening:
    image: urlshortening
    ports:
      - "5431:8080"
    build:
      context: .
      dockerfile: URLShortening/Dockerfile
  postgres:
    image: postgres:latest
    ports:
      - "5430:8080"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata 
    environment:
      POSTGRES_USER: url-shortening
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url-shortening-db
      PGDATA: /var/lib/postgresql/data/pgdata
      
volumes:
  pgdata:
    driver: local